"use strict";
// Antisw MITM Server — intercepts antigravity (Gemini API) → genai.vnpay.vn/aicoding
// No external dependencies — only built-in Node.js modules.
// Certs: rootCA.key + rootCA.crt generated by Rust at ~/.antisw/mitm/

const https = require("https");
const tls   = require("tls");
const fs    = require("fs");
const path  = require("path");
const dns   = require("dns");
const os    = require("os");
const { promisify } = require("util");
const { execSync }  = require("child_process");

// ── Config ────────────────────────────────────────────────────

const LOCAL_PORT = 443;
const IS_WIN     = process.platform === "win32";

const MITM_DIR   = path.join(os.homedir(), ".antisw", "mitm");
const CA_KEY     = path.join(MITM_DIR, "rootCA.key");
const CA_CERT    = path.join(MITM_DIR, "rootCA.crt");

const VNPAY_HOST = "genai.vnpay.vn";
const VNPAY_PATH = "/aicoding";

const ANTIGRAVITY_HOSTS = new Set([
  "daily-cloudcode-pa.googleapis.com",
  "cloudcode-pa.googleapis.com",
]);
const CHAT_PATTERNS = [":generateContent", ":streamGenerateContent"];

const HOST_REWRITE = {
  "cloudcode-pa.googleapis.com": "daily-cloudcode-pa.googleapis.com",
};

// ── Logger ────────────────────────────────────────────────────

const ts  = () => new Date().toLocaleTimeString("en-US", { hour12: false });
const log = (m) => console.log(`[${ts()}] [MITM] ${m}`);
const err = (m) => console.error(`[${ts()}] [MITM] ❌ ${m}`);

// ── SSL — reuse rootCA cert for all domains via SNI ───────────

let rootKey, rootCert;
try {
  rootKey  = fs.readFileSync(CA_KEY);
  rootCert = fs.readFileSync(CA_CERT);
} catch (e) {
  err(`Cannot read Root CA at ${MITM_DIR}: ${e.message}`);
  process.exit(1);
}

// One shared TLS context — rootCA serves as the leaf cert for all intercepted domains.
// Clients must trust the Root CA (install to system keychain).
const sharedCtx = tls.createSecureContext({ key: rootKey, cert: rootCert });

function sniCallback(servername, cb) {
  cb(null, sharedCtx);
}

const sslOptions = { key: rootKey, cert: rootCert, SNICallback: sniCallback };

// ── DNS (passthrough uses real IPs via 8.8.8.8) ───────────────

const ipCache = {};
async function resolveIP(hostname) {
  if (ipCache[hostname] && Date.now() - ipCache[hostname].ts < 300_000)
    return ipCache[hostname].ip;
  const resolver = new dns.Resolver();
  resolver.setServers(["8.8.8.8"]);
  const [ip] = await promisify(resolver.resolve4.bind(resolver))(hostname);
  ipCache[hostname] = { ip, ts: Date.now() };
  return ip;
}

// ── Helpers ───────────────────────────────────────────────────

function collectBody(req) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    req.on("data", (c) => chunks.push(c));
    req.on("end",  () => resolve(Buffer.concat(chunks)));
    req.on("error", reject);
  });
}

async function passthrough(req, res, body) {
  const host       = (req.headers.host || "").split(":")[0];
  const targetHost = HOST_REWRITE[host] || host;
  const ip         = await resolveIP(targetHost);
  const fwd = https.request(
    { hostname: ip, port: 443, path: req.url, method: req.method,
      headers: { ...req.headers, host: targetHost },
      servername: targetHost, rejectUnauthorized: false },
    (fwdRes) => { res.writeHead(fwdRes.statusCode, fwdRes.headers); fwdRes.pipe(res); }
  );
  fwd.on("error", (e) => {
    err(`Passthrough error: ${e.message}`);
    if (!res.headersSent) res.writeHead(502);
    res.end("Bad Gateway");
  });
  if (body.length) fwd.write(body);
  fwd.end();
}

function interceptAntigravity(req, res, body) {
  log(`↗ VNPAY ${req.method} ${req.url} (${body.length}b)`);
  const headers = { ...req.headers, host: VNPAY_HOST };
  delete headers["content-length"];
  delete headers["connection"];
  delete headers["transfer-encoding"];

  const fwd = https.request(
    { hostname: VNPAY_HOST, port: 443, path: VNPAY_PATH, method: req.method,
      headers: { ...headers, "content-length": body.length } },
    (fwdRes) => {
      log(`↙ VNPAY ${fwdRes.statusCode} ${req.url}`);
      res.writeHead(fwdRes.statusCode, fwdRes.headers);
      fwdRes.pipe(res);
    }
  );
  fwd.on("error", async (e) => {
    err(`VNPAY error: ${e.message} — passthrough`);
    await passthrough(req, res, body);
  });
  if (body.length) fwd.write(body);
  fwd.end();
}

// ── Request handler ───────────────────────────────────────────

const server = https.createServer(sslOptions, async (req, res) => {
  try {
    if (req.url === "/_mitm_health") {
      res.writeHead(200, { "Content-Type": "application/json" });
      return res.end(JSON.stringify({ ok: true, pid: process.pid }));
    }

    const body = await collectBody(req);
    const host = (req.headers.host || "").split(":")[0];
    const isAG = ANTIGRAVITY_HOSTS.has(host);
    const isChat = isAG && CHAT_PATTERNS.some((p) => req.url.includes(p));

    log(`${isChat ? "INTERCEPT" : "PASSTHROUGH"} ${req.method} ${host}${req.url} (${body.length}b)`);

    return isChat ? interceptAntigravity(req, res, body) : passthrough(req, res, body);
  } catch (e) {
    err(`Unhandled: ${e.message}`);
    if (!res.headersSent) res.writeHead(500);
    res.end(JSON.stringify({ error: e.message }));
  }
});

// ── Port cleanup ──────────────────────────────────────────────

function killPort(port) {
  try {
    if (IS_WIN) {
      const out = execSync(
        `powershell -NonInteractive -WindowStyle Hidden -Command "Get-NetTCPConnection -LocalPort ${port} -State Listen -ErrorAction SilentlyContinue | Select-Object -ExpandProperty OwningProcess"`,
        { encoding: "utf-8", windowsHide: true }
      ).trim();
      out.split(/\r?\n/).filter((p) => p && +p !== process.pid && +p > 4)
         .forEach((p) => { try { execSync(`taskkill /F /PID ${p}`, { windowsHide: true }); } catch {} });
    } else {
      const out = execSync(`lsof -nP -iTCP:${port} -sTCP:LISTEN -t`, { encoding: "utf-8" }).trim();
      out.split("\n").filter((p) => p && +p !== process.pid)
         .forEach((p) => { try { process.kill(+p, "SIGKILL"); } catch {} });
    }
  } catch (e) { if (e.status !== 1) { err(`killPort: ${e.message}`); process.exit(1); } }
}

killPort(LOCAL_PORT);
server.listen(LOCAL_PORT, () => log(`🚀 Ready on :${LOCAL_PORT}`));
server.on("error", (e) => {
  err(e.code === "EADDRINUSE" ? `Port ${LOCAL_PORT} in use` :
      e.code === "EACCES"     ? `Permission denied :${LOCAL_PORT}` : e.message);
  process.exit(1);
});

// ── Shutdown ──────────────────────────────────────────────────

let down = false;
const shutdown = () => {
  if (down) return; down = true;
  server.close(() => process.exit(0));
  setTimeout(() => process.exit(0), 1500);
};
process.on("SIGTERM", shutdown);
process.on("SIGINT",  shutdown);
if (IS_WIN) process.on("SIGBREAK", shutdown);
